### ISSUE TITLE
This pains me

### ISSUE THREAD

**Issue by Joao-Victor-Bonfim** [SolariusScorch/XComFiles#101]
Why don't they just die while without armour in dimension X?
![Screenshot](https://user-images.githubusercontent.com/23298617/83364954-57f1f100-a37b-11ea-8bc1-36a6332b3fdd.png)

**Comment by SolariusScorch** [comment]
Because they're cyborgs.

**Comment by Joao-Victor-Bonfim** [comment]
> 
> 
> Because they're cyborgs.

But they breathe air.
It doesn't say anywhere that their respiratory system is prepared for outer space survival.

**Comment by SolariusScorch** [comment]
Because in the long run they'd die :) But can withstand a short amount of time.

**Comment by Joao-Victor-Bonfim** [comment]
Maybe add a small damage penalty for them being outside their suits then?
Also The fact that they regenerate all their health is annoying...

**Comment by SolariusScorch** [comment]
I'd have to make a new armour for this (same sprite, different stats)... And that means I'd have to make a new unit too. Which would mean that they would be recovered as a new type of unit, would require new researches, Pedia entries and all that. I don't want to do that, both because it's a lot of unnecessary work and also because it wouldn't look very good to the player.
And they don't "regenerate" anything, they just drop their damaged suit?

**Comment by Joao-Victor-Bonfim** [comment]
Then at least reduce their health while on armour?
It takes a lot of damage for them to leave their suit, which makes combat an ass...

**Comment by SolariusScorch** [comment]
Then I suggest you decrease the difficulty. I'm not going to make them even squishier.
